#!/usr/bin/env python3
"""
tools/compose-tot-addon.py — compose a single ThreadsOfTime AddOn from
per-mod contributions.

Scans:
    modules/<mod>/data/addon-contrib/manifest.toml
    modules/<mod>/data/addon-contrib/*.lua

Produces:
    build/tot-addon/ThreadsOfTime/
        ThreadsOfTime.toc           (auto-generated, lists files in load order)
        00-Core.lua                 (auto-generated, init shim)
        <NN>-<mod>-<filename>.lua   (per-mod contributions, prefixed)

Each mod's contribution lives in its own module dir; the composer just
assembles them into a single addon. Files are PREFIXED (not concatenated)
so per-mod LOC stays attributable in the player's installed AddOn folder
for debugging.

Load order (TOC list order):
    1. 00-Core.lua                  (priority 0, auto-gen)
    2. <NN>-<mod>-<file>.lua        sorted by (mod priority, file index in
                                    manifest.files)

Usage:
    python3 tools/compose-tot-addon.py

After composing, pack the result with modules/mod-warforged/tools/pack-mpq.py.
"""

from __future__ import annotations

import shutil
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODULES = ROOT / "modules"
OUTPUT = ROOT / "build" / "tot-addon" / "ThreadsOfTime"


def discover_contributions() -> list[dict]:
    """Find every modules/<mod>/data/addon-contrib/manifest.toml + its files."""
    contribs = []
    for manifest_path in MODULES.glob("*/data/addon-contrib/manifest.toml"):
        with open(manifest_path, "rb") as f:
            m = tomllib.load(f)
        contrib_dir = manifest_path.parent
        mod_name = m.get("mod", contrib_dir.parent.parent.name)
        priority = m.get("priority", 50)
        files = m.get("files", [])

        resolved = []
        for fname in files:
            fpath = contrib_dir / fname
            if not fpath.exists():
                raise SystemExit(
                    f"{manifest_path} lists {fname} but {fpath} does not exist"
                )
            resolved.append(fpath)
        contribs.append({
            "mod": mod_name,
            "priority": priority,
            "files": resolved,
        })
    contribs.sort(key=lambda c: (c["priority"], c["mod"]))
    return contribs


CORE_LUA = """\
--[[
00-Core.lua — ThreadsOfTime AddOn namespace init.

AUTO-GENERATED by tools/compose-tot-addon.py. DO NOT EDIT BY HAND.

This file runs first (TOC load order) and creates the shared namespace that
every per-mod contribution writes into:

    ThreadsOfTime.Warforged.*
    ThreadsOfTime.BracketSets.*
    ThreadsOfTime.<NextMod>.*

Contributions should guard against double-init:
    ThreadsOfTime = ThreadsOfTime or {}
    ThreadsOfTime.Warforged = ThreadsOfTime.Warforged or {}
]]--

ThreadsOfTime = ThreadsOfTime or {}
ThreadsOfTime.VERSION = "1.0.2"

-- Diagnostic banner so /reload reports composition state.
local n = 0
for k, _ in pairs(ThreadsOfTime) do
    if type(k) == "string" and k:sub(1,1) ~= "_" and k ~= "VERSION" then
        n = n + 1
    end
end
-- (Banner suppressed at load — modules emit their own banners.)
"""


TOC_TEMPLATE = """\
## Interface: 30300
## Title: Threads of Time
## Notes: Server-driven client renderer for Threads of Time content mods (Warforged tooltips, bracket-set bonuses, etc.). Composed at release-time from modules/*/data/addon-contrib/.
## Author: Threads of Time
## Version: {version}
## DefaultState: enabled
## LoadOnDemand: 0

{file_list}
"""


def compose() -> Path:
    contribs = discover_contributions()
    if not contribs:
        raise SystemExit(
            "No contributions found. Each contributing mod needs "
            "modules/<mod>/data/addon-contrib/manifest.toml."
        )

    # Wipe + recreate output staging
    if OUTPUT.exists():
        shutil.rmtree(OUTPUT)
    OUTPUT.mkdir(parents=True)

    # 1. Core init file (priority 0)
    (OUTPUT / "00-Core.lua").write_text(CORE_LUA)
    toc_files = ["00-Core.lua"]

    # 2. Per-mod contributions, prefixed by (priority, file-index)
    for contrib in contribs:
        # Strip the "mod-" prefix from the AddOn-side filename — it's noise
        mod_short = contrib["mod"]
        if mod_short.startswith("mod-"):
            mod_short = mod_short[4:]
        # Convert dashes to PascalCase-ish for filenames
        mod_short = "".join(part.capitalize() for part in mod_short.split("-"))

        for idx, src in enumerate(contrib["files"], start=1):
            # e.g., "10-Warforged-01-WarforgedStatBumps.lua"
            dst_name = f"{contrib['priority']:02d}-{mod_short}-{idx:02d}-{src.name}"
            shutil.copy2(src, OUTPUT / dst_name)
            toc_files.append(dst_name)
            print(f"  + {dst_name:<60s} <- {src.relative_to(ROOT)}")

    # 3. TOC manifest
    toc = TOC_TEMPLATE.format(
        version=os.environ.get("TOT_ADDON_VERSION", "1.0.2"),
        file_list="\n".join(toc_files),
    )
    (OUTPUT / "ThreadsOfTime.toc").write_text(toc)
    print(f"  + ThreadsOfTime.toc")

    print(f"\nComposed {OUTPUT} ({len(toc_files)} Lua files, {len(contribs)} contributing mods)")
    return OUTPUT


if __name__ == "__main__":
    import os
    try:
        compose()
    except SystemExit:
        raise
    except Exception as exc:
        print(f"compose-tot-addon.py: {exc}", file=sys.stderr)
        sys.exit(1)
