-- world_sod_loot.sql — auto-generated by sod-import.py
-- DO NOT EDIT BY HAND: re-run `python3 sod-import.py items` to regenerate
-- NOTE: creature_entry=0 rows are placeholders — update with real NPC IDs (Task 10)

SET NAMES utf8mb4;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;


-- === Blackfathom Deeps ===

-- Baron Aquanis (npc=202699) → Hydraxian Bangles (custom_id=90000, 5.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (202699, 90000, 0, 5.0, 0, 1, 0, 1, 1, 'SoD import');
-- Baron Aquanis (npc=202699) → Fathomblade (custom_id=90001, 5.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (202699, 90001, 0, 5.0, 0, 1, 0, 1, 1, 'SoD import');
-- Ghamoo-ra (npc=201722) → Adamantine Tortoise Armor (custom_id=90002, 5.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (201722, 90002, 0, 5.0, 0, 1, 0, 1, 1, 'SoD import');
-- Baron Aquanis (npc=202699) → Cord of Aquanis (custom_id=90003, 5.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (202699, 90003, 0, 5.0, 0, 1, 0, 1, 1, 'SoD import');
-- Baron Aquanis (npc=202699) → High Tide Choker (custom_id=90004, 5.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (202699, 90004, 0, 5.0, 0, 1, 0, 1, 1, 'SoD import');
-- Baron Aquanis (npc=202699) → Flowing Scarf (custom_id=90005, 5.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (202699, 90005, 0, 5.0, 0, 1, 0, 1, 1, 'SoD import');
-- Ghamoo-ra (npc=201722) → Shell Plate Barrier (custom_id=90006, 5.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (201722, 90006, 0, 5.0, 0, 1, 0, 1, 1, 'SoD import');
-- Ghamoo-ra (npc=201722) → Ghamoo-ra's Cinch (custom_id=90007, 5.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (201722, 90007, 0, 5.0, 0, 1, 0, 1, 1, 'SoD import');
-- Ghamoo-ra (npc=201722) → Chipped Bite of Serra'kis (custom_id=90008, 5.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (201722, 90008, 0, 5.0, 0, 1, 0, 1, 1, 'SoD import');
-- Ghamoo-ra (npc=201722) → Shimmering Thresher Cape (custom_id=90009, 5.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (201722, 90009, 0, 5.0, 0, 1, 0, 1, 1, 'SoD import');
-- Ghamoo-ra (npc=201722) → Bindings of Serra'kis (custom_id=90010, 5.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (201722, 90010, 0, 5.0, 0, 1, 0, 1, 1, 'SoD import');
-- Lady Sarevess (npc=204068) → Honed Darkwater Talwar (custom_id=90011, 5.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (204068, 90011, 0, 5.0, 0, 1, 0, 1, 1, 'SoD import');
-- Lady Sarevess (npc=204068) → Naga Battle Gauntlets (custom_id=90012, 5.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (204068, 90012, 0, 5.0, 0, 1, 0, 1, 1, 'SoD import');
-- Aku'mai (npc=213334) → Azshari Arbalest (custom_id=90013, 5.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (213334, 90013, 0, 5.0, 0, 1, 0, 1, 1, 'SoD import');
-- Gelihast (npc=204921) → Twilight Sage's Walking Stick (custom_id=90014, 5.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (204921, 90014, 0, 5.0, 0, 1, 0, 1, 1, 'SoD import');
-- Lorgus Jett (npc=207356) → Hammer of Righteous Judgement (custom_id=90015, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (207356, 90015, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Twilight Lord Kelris (npc=209678) → Rod of the Ancient Sleepwalker (custom_id=90016, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (209678, 90016, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Aku'mai (npc=213334) → Deadly Strike of the Hydra (custom_id=90017, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (213334, 90017, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Lady Sarevess (npc=204068) → Naga Heartrender (custom_id=90018, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (204068, 90018, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Lady Sarevess (npc=204068) → Guardian's Trident (custom_id=90019, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (204068, 90019, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Lady Sarevess (npc=204068) → Band of Deep Places (custom_id=90020, 1.5%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (204068, 90020, 0, 1.5, 0, 1, 0, 1, 1, 'SoD import');
-- Lady Sarevess (npc=204068) → Leggings of the Faithful (custom_id=90021, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (204068, 90021, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Gelihast (npc=204921) → Coral Reef Axe (custom_id=90022, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (204921, 90022, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Gelihast (npc=204921) → Algae Gauntlets (custom_id=90023, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (204921, 90023, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Gelihast (npc=204921) → Murloc Hide Kneeboots (custom_id=90024, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (204921, 90024, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Gelihast (npc=204921) → Tome of Cavern Lore (custom_id=90025, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (204921, 90025, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Gelihast (npc=204921) → Deadlight (custom_id=90026, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (204921, 90026, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Gelihast (npc=204921) → Black Boiled Leathers (custom_id=90027, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (204921, 90027, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Gelihast (npc=204921) → Wrathful Spire (custom_id=90028, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (204921, 90028, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Lorgus Jett (npc=207356) → Discarded Tenets of the Silver Hand (custom_id=90029, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (207356, 90029, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Lorgus Jett (npc=207356) → Carved Driftwood Icon (custom_id=90030, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (207356, 90030, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Lorgus Jett (npc=207356) → Mind-Expanding Mushroom (custom_id=90031, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (207356, 90031, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Lorgus Jett (npc=207356) → Fist of the Wild (custom_id=90032, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (207356, 90032, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Lorgus Jett (npc=207356) → Glowing Leather Bands (custom_id=90033, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (207356, 90033, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Lorgus Jett (npc=207356) → Crashing Thunder (custom_id=90034, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (207356, 90034, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Aku'mai (npc=213334) → Gusting Wind (custom_id=90035, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (213334, 90035, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Lorgus Jett (npc=207356) → Silver Hand Sabatons (custom_id=90036, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (207356, 90036, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Baron Aquanis (npc=202699) → Cracked Water Globe (custom_id=90037, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (202699, 90037, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Twilight Lord Kelris (npc=209678) → Gaze Dreamer Leggings (custom_id=90038, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (209678, 90038, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Twilight Lord Kelris (npc=209678) → Signet of the Twilight Lord (custom_id=90039, 1.5%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (209678, 90039, 0, 1.5, 0, 1, 0, 1, 1, 'SoD import');
-- Blackfathom Deeps (npc=0) → Twilight Invoker's Shoes (custom_id=90040, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (0, 90040, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Gelihast (npc=204921) → Skinwalkers (custom_id=90041, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (204921, 90041, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Blackfathom Deeps (npc=0) → Twilight Invoker's Robes (custom_id=90042, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (0, 90042, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Twilight Lord Kelris (npc=209678) → Black Fingerless Gloves (custom_id=90043, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (209678, 90043, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Twilight Lord Kelris (npc=209678) → Glowing Fetish Amulet (custom_id=90044, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (209678, 90044, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Twilight Lord Kelris (npc=209678) → Phoenix Ignition (custom_id=90045, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (209678, 90045, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Ghamoo-ra (npc=201722) → Clamweave Tunic (custom_id=90046, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (201722, 90046, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Baron Aquanis (npc=202699) → Shoulderguards of Crushing Depths (custom_id=90047, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (202699, 90047, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');
-- Baron Aquanis (npc=202699) → Loop of Swift Currents (custom_id=90048, 1.5%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (202699, 90048, 0, 1.5, 0, 1, 0, 1, 1, 'SoD import');
-- Ghamoo-ra (npc=201722) → Mantle of the Thresher Slayer (custom_id=90049, 8.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (201722, 90049, 0, 8.0, 0, 1, 0, 1, 1, 'SoD import');

-- === Shadowfang Keep ===

-- Sever (npc=14682) → The Axe of Severing (custom_id=90050, 5.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (14682, 90050, 0, 5.0, 0, 1, 0, 1, 1, 'SoD import');
-- Sever (npc=14682) → Abomination Skin Leggings (custom_id=90051, 5.0%)
INSERT IGNORE INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (14682, 90051, 0, 5.0, 0, 1, 0, 1, 1, 'SoD import');

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
