--[[
GameTooltip.lua — mod-warforged FrameXML override (v1.0)

Hooks GameTooltip:OnTooltipSetItem and rewrites the tooltip when the item's
BONUS_ENCHANTMENT_SLOT (enchant slot 5 in the item link) holds a Warforged
enchant ID (70001..70063):

  1. Bumps the displayed "Item Level NN" line by +5.
  2. Suppresses the default green "Warforged: +X Strength" enchant line at
     the bottom of the tooltip (the client renders this automatically from
     the patched SpellItemEnchantment.dbc; we hide it because the orange
     tag + bumped ilvl already communicates the affix).
  3. Appends an orange "Warforged" tag line to the tooltip.

Caveat — the v1.0 tag is appended at the bottom via tooltip:AddLine. Putting
the tag literally under the item name (line 2) requires FontString reordering
which is tracked as v1.1 polish in the README.

The stat-bump folding step (rewriting base stat lines to include the enchant
bumps inline) is also deferred to v1.1 — for v1.0, the suppressed default
enchant line + orange tag is the MVP. WarforgedStatBumps.lua is generated by
tools/build-warforged-dbc.py so v1.1 can consume it without churning the
build pipeline.

WoW 3.3.5a item link format:
  |c<color>|Hitem:<entry>:<e0>:<e1>:<e2>:<e3>:<e4>:<e5>:<seed>:<context>|h[<name>]|h|r
e5 = BONUS_ENCHANTMENT_SLOT. After strsplit(":", link), parts[8] is e5.
]]--

WARFORGED_PATCH_VERSION = "1.0.0"

local WF_ENCH_MIN, WF_ENCH_MAX = 70001, 70063
local WF_TAG_COLOR = "|cffff8000"
local WF_ILVL_BUMP = 5

local function IsWarforgedEnchant(id)
    id = tonumber(id) or 0
    return id >= WF_ENCH_MIN and id <= WF_ENCH_MAX
end

local function GetBonusEnchantFromLink(itemLink)
    if not itemLink then return 0 end
    local parts = { strsplit(":", itemLink) }
    -- parts[1] = "...|Hitem", parts[2]=entry, parts[3..8]=e0..e5
    return tonumber(parts[8] or "0") or 0
end

local function FormatTooltipForWarforged(tooltip, bonusEnchantId)
    local name = tooltip:GetName()
    local numLines = tooltip:NumLines()

    -- 1. Bump the "Item Level NN" line by +5.
    for i = 1, numLines do
        local line = _G[name .. "TextLeft" .. i]
        if line then
            local text = line:GetText() or ""
            local ilvl = text:match("^Item Level (%d+)$")
            if ilvl then
                line:SetText("Item Level " .. (tonumber(ilvl) + WF_ILVL_BUMP))
            end
        end
    end

    -- 2. Suppress the default "Warforged: ..." enchant line that the client
    --    renders from the patched DBC.
    for i = 1, numLines do
        local line = _G[name .. "TextLeft" .. i]
        if line then
            local text = line:GetText() or ""
            if text:match("^Warforged:") then
                line:SetText("")
            end
        end
    end

    -- 3. Append the orange Warforged tag. (v1.1 polish: reorder to sit under
    --    the item name instead of at the bottom.)
    tooltip:AddLine(WF_TAG_COLOR .. "Warforged|r")

    -- 4. Force re-layout so the suppressed line collapses and the tag shows.
    tooltip:Show()
end

GameTooltip:HookScript("OnTooltipSetItem", function(self)
    local _, itemLink = self:GetItem()
    if not itemLink then return end
    local bonusId = GetBonusEnchantFromLink(itemLink)
    if IsWarforgedEnchant(bonusId) then
        FormatTooltipForWarforged(self, bonusId)
    end
end)
