-- AUTO-GENERATED by tools/build-warforged-dbc.py from data/csv/warforged_enchants.csv
-- DO NOT EDIT BY HAND. Re-run the build script to regenerate.
--
-- Maps each Warforged enchant ID (70001..70063) to the stat bumps it
-- applies, so the FrameXML override can fold them inline into the
-- displayed stat lines instead of showing them as a separate enchant.
WF_STAT_BUMPS = {
    [70001] = { str=1, sta=1, crit=1 },
    [70002] = { str=1, sta=1, crit=1 },
    [70003] = { str=2, sta=2, crit=2 },
    [70011] = { str=1, sta=1, crit=1 },
    [70012] = { str=1, sta=1, crit=1 },
    [70013] = { str=1, sta=1, crit=1 },
    [70021] = { str=1, sta=1, crit=1 },
    [70022] = { str=1, sta=1, crit=1 },
    [70023] = { str=2, sta=2, crit=1 },
    [70031] = { str=2, sta=2, crit=2 },
    [70032] = { str=3, sta=2, crit=2 },
    [70033] = { str=3, sta=2, crit=2 },
    [70041] = { str=4, sta=3, crit=3 },
    [70042] = { str=4, sta=3, crit=3 },
    [70043] = { str=4, sta=3, crit=3 },
    [70051] = { str=5, sta=4, crit=6 },
    [70052] = { str=5, sta=5, crit=5 },
    [70053] = { str=6, sta=5, crit=4 },
    [70061] = { str=11, sta=10, crit=8 },
    [70062] = { str=13, sta=12, crit=9 },
    [70063] = { str=12, sta=10, crit=8 },
}
