"""Generate a harness config fixture YAML with a given listen_address and ac_bridge_url.

Usage:
  python make_fixture.py <listen_address> <ac_bridge_url> <audit_path>

Outputs YAML to stdout.
"""
from __future__ import annotations

import sys
import tempfile


def make_fixture_yaml(
    listen_address: str,
    ac_bridge_url: str,
    audit_path: str,
) -> str:
    return f"""# Auto-generated by parity/make_fixture.py
max_augmented_bots: 10
ac_bridge_url: "{ac_bridge_url}"
audit_path: "{audit_path}"
listen_address: "{listen_address}"

tokens:
  - token: "parity-all"
    identity: "parity.user"
    scope:
      - "gm.*"
      - "bot.*"
      - "obs.*"
      - "event.*"
      - "lfg.*"
      - "memory.*"
    note: "parity gate: full-scope token"

  - token: "parity-self"
    identity: "bot.self"
    scope:
      - "bot.self.*"
      - "obs.self.*"
    bound_to_guid: 777
    augmented: true
    note: "parity gate: self-bound token"

  - token: "parity-obs"
    identity: "parity.obs"
    scope:
      - "obs.*"
    note: "parity gate: obs-only token for scope_denied tests"
"""


if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("usage: make_fixture.py <listen_addr> <ac_bridge_url> <audit_path>", file=sys.stderr)
        sys.exit(1)
    print(make_fixture_yaml(sys.argv[1], sys.argv[2], sys.argv[3]), end="")
